import { AppLayout } from "@/components/layout/app-layout";
import { API_BASE_URL } from "@/api/client";
import { requireSupabase } from "@/lib/supabase";
import { useEffect,useState } from "react";
type Upload={id:number;paper_id:number|null;original_filename:string;status:string;error_message:string|null;created_at:string};
export default function PaperTesting(){const [uploads,setUploads]=useState<Upload[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState<number|null>(null);
  async function load(){const {data}=await requireSupabase().from("uploads").select("id,paper_id,original_filename,status,error_message,created_at").order("created_at",{ascending:false}).limit(30);setUploads((data??[]) as Upload[])}
  useEffect(()=>{void load()},[]);
  async function process(paperId:number){setBusy(paperId);setMessage("");const client=requireSupabase();const {data}=await client.auth.getSession();try{const r=await fetch(`${API_BASE_URL}/api/papers/${paperId}/process`,{method:"POST",headers:{Authorization:`Bearer ${data.session?.access_token}`}});const body=await r.json();if(!r.ok)throw new Error(body.error??"Processing failed");setMessage(`Extracted ${body.extracted} real questions; AI classified ${body.aiClassified}.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Processing failed")}finally{setBusy(null)}}
  return <AppLayout><div className="space-y-6"><div><h1 className="text-3xl font-bold text-[#0B1F3A]">Paper pipeline testing</h1><p className="text-gray-500">Verify uploads, extraction status, topics, and database writes.</p></div>{message&&<p className="rounded-xl bg-cyan-50 p-4 text-sm text-[#0B1F3A]">{message}</p>}<div className="overflow-hidden rounded-2xl border bg-white"><div className="grid grid-cols-[1fr_140px_130px] gap-3 border-b bg-slate-50 p-4 text-xs font-bold uppercase text-gray-500"><span>PDF</span><span>Status</span><span>Action</span></div>{uploads.map(u=><div key={u.id} className="grid grid-cols-[1fr_140px_130px] items-center gap-3 border-b p-4 text-sm"><div><b className="text-[#0B1F3A]">{u.original_filename}</b>{u.error_message&&<p className="text-xs text-red-600">{u.error_message}</p>}</div><span>{u.status}</span><button disabled={!u.paper_id||busy===u.paper_id} onClick={()=>u.paper_id&&process(u.paper_id)} className="rounded-lg bg-[#0B1F3A] px-3 py-2 text-white disabled:opacity-40">{busy===u.paper_id?"Processing…":"Process"}</button></div>)}{!uploads.length&&<p className="p-10 text-center text-gray-500">No real uploads yet.</p>}</div></div></AppLayout>}
