import { AppLayout } from "@/components/layout/app-layout";
import { API_BASE_URL } from "@/api/client";
import { requireSupabase } from "@/lib/supabase";
import { useEffect,useMemo,useState } from "react";
import { AlertTriangle,CheckCircle2,ClipboardCheck,FileUp,Loader2 } from "lucide-react";
import { filenameHints, mismatchMessage } from "./paper-checker-filename";

type Paper={id:number;year:number;session:string;paper_number:number|null;paper_code:string|null;variant:number;original_filename:string|null;question_paper_code:string|null;indexed_question_count:number;verified_question_count:number;marking_scheme_linked_count:number;indexed_question_number_count:number;verified_question_number_count:number;marking_scheme_linked_question_count:number;expected_question_count:number|null;subjects:{name:string;code:string}|Array<{name:string;code:string}>};
type Extracted={id:number;question_id:number;question_number:string;question_part:string|null;extracted_answer_text:string;corrected_answer_text:string|null;extraction_confidence:number;needs_student_review:boolean};
type Result={id:number;question_number:string;topic:string;studentAnswer:string;maxMarks:number;awardedMarks:number|null;correctPoints:string[];missingPoints:string[];mistakeType:string|null;feedback:string;examinerTip:string;markingStatus:string};
type Similar={id:number;question_number:string;topic:string;subtopic:string|null;year:number;session:string;paper_code:string;variant:number};
type Report={totalAwarded:number;totalPossible:number;percentage:number;results:Result[];similarQuestions:Similar[]};
async function token(){return(await requireSupabase().auth.getSession()).data.session?.access_token??""}
async function jsonApi(path:string,init?:RequestInit){const r=await fetch(`${API_BASE_URL}/api${path}`,{...init,headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json",...(init?.headers??{})}});const b=await r.json();if(!r.ok)throw new Error(b.error??"Request failed.");return b}
const sessionName=(v:string)=>v.replace("MAY_JUNE","May/June").replace("OCT_NOV","Oct/Nov").replace("FEB_MAR","Feb/Mar");
export default function PaperChecker(){
 const[papers,setPapers]=useState<Paper[]>([]),[paperId,setPaperId]=useState(""),[file,setFile]=useState<File|null>(null),[stage,setStage]=useState<"choose"|"processing"|"review"|"report">("choose"),[progress,setProgress]=useState(""),[submissionId,setSubmissionId]=useState(""),[answers,setAnswers]=useState<Extracted[]>([]),[message,setMessage]=useState(""),[error,setError]=useState(""),[report,setReport]=useState<Report|null>(null);
 useEffect(()=>{jsonApi("/paper-checker/papers").then(v=>{setPapers(v.papers);if(!v.papers.length)setError("No indexed papers found. Upload and process question papers first.")}).catch(e=>setError(`Could not load papers: ${e.message}`))},[]);
 const selected=papers.find(p=>p.id===Number(paperId)),subject=(p:Paper)=>Array.isArray(p.subjects)?p.subjects[0]:p.subjects;
 const grouped=useMemo(()=>papers.reduce<Record<string,Paper[]>>((o,p)=>{(o[`${subject(p)?.name} ${subject(p)?.code}`]??=[]).push(p);return o},{}),[papers]);
 const hints=useMemo(()=>filenameHints(file?.name??""),[file?.name]),mismatch=mismatchMessage(selected,file?.name,hints);
 const isPartial=Boolean(selected?.expected_question_count&&selected.verified_question_number_count<selected.expected_question_count);
 const noScheme=Boolean(selected&&selected.marking_scheme_linked_question_count===0);
 const partialScheme=Boolean(selected&&selected.marking_scheme_linked_question_count>0&&selected.marking_scheme_linked_question_count<selected.verified_question_number_count);
 async function upload(){if(!file||!paperId){setError("Select an indexed paper and choose a PDF first.");return}setStage("processing");setProgress("Uploading PDF…");setError("");const form=new FormData();form.append("file",file);form.append("resourceId",paperId);try{const r=await fetch(`${API_BASE_URL}/api/paper-checker/submissions`,{method:"POST",headers:{Authorization:`Bearer ${await token()}`},body:form});setProgress("Reading answers…");const b=await r.json();if(!r.ok)throw new Error(b.error??"Upload failed. Please try again.");setSubmissionId(b.submissionId);setAnswers(b.answers);setMessage(b.message??(b.extractionStatus==="needs_manual_review"?"Your PDF was uploaded, but handwriting extraction is not configured yet. You can manually enter or correct detected answers before checking.":"Ready to review answers."));setProgress(b.extractionStatus==="needs_manual_review"?"Extraction needs review":"Ready to review answers");setStage("review")}catch(e){setError(e instanceof Error?e.message:"Upload failed. Please try again.");setStage("choose")}}
 async function check(){setStage("processing");setProgress("Checking answers and preparing report…");try{const r=await jsonApi("/paper-checker/check",{method:"POST",body:JSON.stringify({resourceId:Number(paperId),submissionId,answers:answers.map(a=>({questionId:a.question_id,answer:a.corrected_answer_text??a.extracted_answer_text}))})});setReport(r);setStage("report")}catch(e){setError(e instanceof Error?e.message:"Marking failed for some answers. You can retry.");setStage("review")}}
 return <AppLayout><div className="mx-auto max-w-5xl space-y-6"><header className="rounded-3xl bg-gradient-to-br from-[#0B1F3A] to-[#123C5A] p-7 text-white"><div className="flex items-center gap-2 text-cyan-200"><ClipboardCheck className="h-5 w-5"/>Paper Checker</div><h1 className="mt-3 text-3xl font-bold">Upload your solved paper</h1><p className="mt-2 text-sm text-slate-200">Upload a clear scanned PDF of your solved paper. Make sure question numbers are visible.</p></header>
 <div className="grid grid-cols-4 gap-2">{["Choose paper","Upload PDF","Review answers","Report"].map((s,i)=><div key={s} className={`rounded-xl p-2 text-center text-xs font-semibold ${(["choose","processing","review","report"].indexOf(stage)>=i)?"bg-cyan-100 text-cyan-800":"bg-white text-slate-400"}`}>{i+1}. {s}</div>)}</div>{error&&<p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
 {stage==="choose"&&<section className="rounded-2xl border bg-white p-6 shadow-sm">
  <h2 className="font-bold text-[#0B1F3A]">1. Choose your Cambridge paper</h2>
  <select className="field-input mt-4 w-full" value={paperId} onChange={e=>paperId!==e.target.value&&setPaperId(e.target.value)}>
   <option value="">Select paper</option>
   {Object.entries(grouped).map(([name,rows])=><optgroup key={name} label={name}>{rows.map(p=><option key={p.id} value={p.id}>{subject(p)?.name} {subject(p)?.code} · {p.year} {sessionName(p.session)} · Paper {p.paper_number??p.paper_code} Variant {p.variant} · Code: {p.question_paper_code??"unknown"}{p.expected_question_count&&p.verified_question_number_count<p.expected_question_count?` · Partially indexed — only ${p.verified_question_number_count} verified questions available`:""}</option>)}</optgroup>)}
  </select>
  {selected&&<div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm">
   <p className="text-xs font-bold uppercase tracking-wide text-slate-500">Selected paper</p>
   <b className="mt-2 block text-base text-[#0B1F3A]">{subject(selected)?.name} {subject(selected)?.code}</b>
   <p>{sessionName(selected.session)} {selected.year}</p>
   <p>Paper {selected.paper_number??selected.paper_code} Variant {selected.variant}</p>
   <p className="mt-2 font-mono text-xs">Code: {selected.question_paper_code??"Unavailable"}</p>
   <div className="mt-3 grid gap-2 text-xs sm:grid-cols-3">
    <span className="rounded-lg bg-white p-2">{selected.indexed_question_count} indexed rows</span>
    <span className="rounded-lg bg-white p-2">{selected.verified_question_number_count}{selected.expected_question_count?` / ${selected.expected_question_count}`:""} verified questions</span>
    <span className="rounded-lg bg-white p-2">{selected.marking_scheme_linked_question_count}{selected.verified_question_number_count?` / ${selected.verified_question_number_count}`:""} linked questions</span>
   </div>
   {isPartial&&<p className="mt-3 flex gap-2 rounded-lg bg-amber-100 p-3 font-semibold text-amber-900"><AlertTriangle className="h-5 w-5 shrink-0"/>This paper is not fully indexed yet. Paper Checker can only check {selected.verified_question_number_count} verified questions.</p>}
   {!selected.expected_question_count&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-amber-800">The expected question count is unknown. You can test this paper, but confirm its coverage first.</p>}
   {noScheme&&<p className="mt-3 rounded-lg bg-red-50 p-3 font-semibold text-red-800">No marking scheme answers are linked. You may upload and review answers, but checking is unavailable until an admin links the marking scheme.</p>}
   {partialScheme&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-amber-800">Only {selected.marking_scheme_linked_question_count} of {selected.verified_question_number_count} verified questions have marking-scheme links. The report will be incomplete.</p>}
  </div>}
  <label className="mt-5 flex cursor-pointer flex-col items-center rounded-2xl border-2 border-dashed border-cyan-200 p-10 text-center hover:bg-cyan-50">
   <FileUp className="h-8 w-8 text-cyan-600"/><b className="mt-3">Choose solved-paper PDF</b><span className="mt-1 text-xs text-slate-500">PDF only · maximum 25 MB · typed, scanned, or handwritten</span>
   <input type="file" accept="application/pdf" className="hidden" onChange={e=>setFile(e.target.files?.[0]??null)}/>
   {file&&<span className="mt-3 rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-700">{file.name}</span>}
  </label>
  {mismatch&&<p className="mt-4 flex gap-2 rounded-xl bg-amber-100 p-4 text-sm font-semibold text-amber-900"><AlertTriangle className="h-5 w-5 shrink-0"/>{mismatch}</p>}
  {import.meta.env.DEV&&selected&&<details className="mt-4 rounded-xl border border-dashed bg-slate-50 p-3 text-xs text-slate-600"><summary className="cursor-pointer font-semibold">Development debug</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap">{JSON.stringify({selectedPaper:selected,selectedFile:file?.name??null,filenameHints:hints,mismatch:mismatch||null,eligibility:{upload:Boolean(file&&selected),check:!noScheme}},null,2)}</pre></details>}
  <button disabled={!paperId||!file} onClick={upload} className="mt-5 w-full rounded-xl bg-teal-600 p-3 font-bold text-white disabled:opacity-40">Upload and read answers</button>
 </section>}
 {stage==="processing"&&<section className="rounded-2xl border bg-white p-12 text-center"><Loader2 className="mx-auto h-9 w-9 animate-spin text-teal-600"/><h2 className="mt-4 font-bold">{progress||"Processing your solved paper…"}</h2><div className="mt-4 space-y-1 text-sm text-slate-500"><p>Uploading file</p><p>Reading pages and detecting question numbers</p><p>Matching answers to your selected paper</p><p>Preparing review</p></div></section>}
 {stage==="review"&&<section className="space-y-4"><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">3. Review extracted answers</h2><p className="mt-2 text-sm text-amber-700">{message}</p><p className="mt-1 text-sm text-slate-500">Correct OCR text before marking. Blank boxes are treated as unanswered.</p>{noScheme&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-800">Checking is unavailable because this paper has no linked marking-scheme answers.</p>}</div>{answers.map((a,i)=><article key={a.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><b>Q{a.question_number}</b><span className="text-xs text-slate-400">{Math.round(a.extraction_confidence*100)}% extraction confidence</span></div><textarea rows={4} className="field-input mt-3 w-full" value={a.corrected_answer_text??a.extracted_answer_text} onChange={e=>setAnswers(v=>v.map((x,j)=>j===i?{...x,corrected_answer_text:e.target.value}:x))}/></article>)}<button disabled={noScheme} onClick={check} className="w-full rounded-xl bg-teal-600 p-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">I reviewed these answers — Check My Paper</button></section>}
 {stage==="report"&&report&&<><section className="rounded-3xl border bg-white p-6"><div className="flex items-center gap-2 text-emerald-700"><CheckCircle2 className="h-5 w-5"/>Report ready</div><div className="mt-5 grid grid-cols-3 gap-3"><Summary l="Score" v={`${report.totalAwarded} / ${report.totalPossible}`}/><Summary l="Percentage" v={`${report.percentage}%`}/><Summary l="Checked" v={String(report.results.length)}/></div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm">Grade threshold is not uploaded yet, so grade estimate is unavailable. Your percentage is shown instead.</p><p className="mt-2 text-sm text-slate-500">Examiner report is not uploaded yet, so feedback is based on the marking scheme and your answer.</p></section>{report.results.map(r=><article key={r.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><b>Q{r.question_number} · {r.topic}</b><b>{r.awardedMarks??"—"} / {r.maxMarks}</b></div><p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>Your answer:</b> {r.studentAnswer||"Unanswered"}</p><p className="mt-3 text-sm">{r.feedback}</p>{r.missingPoints.length>0&&<p className="mt-2 text-sm text-amber-800"><b>Missing:</b> {r.missingPoints.join("; ")}</p>}<p className="mt-2 text-sm text-violet-700"><b>Improve:</b> {r.examinerTip}</p></article>)}{report.similarQuestions.length>0&&<section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Similar practice questions</h2>{report.similarQuestions.map(q=><p key={q.id} className="mt-2 text-sm">{q.year} {sessionName(q.session)} · Paper {q.paper_code} Variant {q.variant} · Q{q.question_number} · {q.topic}</p>)}</section>}</>}
 </div></AppLayout>
}
function Summary({l,v}:{l:string;v:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{l}</p><p className="mt-1 text-xl font-bold">{v}</p></div>}
