alter table public.question_index
  add column if not exists verification_status text not null default 'auto_detected'
    check (verification_status in ('auto_detected','needs_review','verified','rejected')),
  add column if not exists extraction_confidence numeric(4,3)
    check (extraction_confidence is null or extraction_confidence between 0 and 1),
  add column if not exists formula_usage text[] not null default '{}',
  add column if not exists command_words text[] not null default '{}';

alter table public.marking_scheme_answers
  add column if not exists question_id bigint references public.question_index(id) on delete set null,
  add column if not exists subject_id bigint references public.subjects(id) on delete set null,
  add column if not exists syllabus_code text,
  add column if not exists year integer,
  add column if not exists session text,
  add column if not exists paper_number integer,
  add column if not exists variant integer,
  add column if not exists alternatives_json jsonb not null default '[]',
  add column if not exists examiner_notes text,
  add column if not exists link_confidence numeric(4,3)
    check (link_confidence is null or link_confidence between 0 and 1),
  add column if not exists linked_status text not null default 'unlinked'
    check (linked_status in ('linked','partial','unlinked','needs_review')),
  add column if not exists verification_status text not null default 'auto_detected'
    check (verification_status in ('auto_detected','needs_review','verified','rejected')),
  add column if not exists updated_at timestamptz not null default now();

alter table public.resource_chunks
  add column if not exists confidence numeric(4,3)
    check (confidence is null or confidence between 0 and 1),
  add column if not exists verification_status text not null default 'auto_detected'
    check (verification_status in ('auto_detected','needs_review','verified','rejected')),
  add column if not exists updated_at timestamptz not null default now();

alter table public.fine_tuning_examples
  add column if not exists source_ids jsonb not null default '[]',
  add column if not exists approved_by uuid references auth.users(id) on delete set null,
  add column if not exists approved_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.student_performance_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  question_id bigint references public.question_index(id) on delete set null,
  submission_id uuid references public.paper_check_submissions(id) on delete set null,
  event_type text not null default 'paper_checker',
  topic text,
  subtopic text,
  marks_available numeric,
  marks_scored numeric,
  mistake_type text,
  feedback_json jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists student_performance_events_owner_idx
  on public.student_performance_events(user_id, subject_id, created_at desc);

alter table public.student_performance_events enable row level security;
grant select,insert,update,delete on public.student_performance_events to authenticated;
grant usage,select on sequence public.student_performance_events_id_seq to authenticated;
create policy "Performance events owned access" on public.student_performance_events
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

