alter table public.question_index
  add column if not exists marking_scheme_status text not null default 'resource_missing'
    check (marking_scheme_status in ('linked','resource_missing','resource_exists_answer_missing','answer_extracted_not_linked','answer_not_extracted','needs_review','generic_guidance_only','invalid_link'));

alter table public.marking_scheme_answers
  add column if not exists level text,
  add column if not exists component_variant_code text,
  add column if not exists answer_text text,
  add column if not exists marking_points_json jsonb not null default '[]'::jsonb,
  add column if not exists raw_text text,
  add column if not exists bounding_box jsonb,
  add column if not exists crop_path text,
  add column if not exists page_preview_path text,
  add column if not exists preview_status text not null default 'not_generated'
    check (preview_status in ('not_generated','generated','full_page_fallback','failed','needs_review'));

create table if not exists public.resource_links (
  id bigint generated by default as identity primary key,
  question_paper_resource_id bigint not null references public.resources(id) on delete cascade,
  marking_scheme_resource_id bigint not null references public.resources(id) on delete cascade,
  link_type text not null default 'question_paper_to_marking_scheme'
    check (link_type='question_paper_to_marking_scheme'),
  match_status text not null default 'matched'
    check (match_status in ('matched','needs_review','invalid')),
  match_confidence numeric(4,3) not null default 1 check (match_confidence between 0 and 1),
  mismatch_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(question_paper_resource_id,marking_scheme_resource_id,link_type)
);

create table if not exists public.ai_health_eval_runs (
  id bigint generated by default as identity primary key,
  eval_type text not null check (eval_type in ('coverage','dynamic','marking_links','regression')),
  status text not null check (status in ('passed','failed','partial')),
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.resource_links enable row level security;
alter table public.ai_health_eval_runs enable row level security;

create policy "Admins manage resource links" on public.resource_links for all to authenticated
using (exists(select 1 from public.admin_users where lower(email)=lower(auth.jwt()->>'email')))
with check (exists(select 1 from public.admin_users where lower(email)=lower(auth.jwt()->>'email')));
create policy "Admins read AI health runs" on public.ai_health_eval_runs for select to authenticated
using (exists(select 1 from public.admin_users where lower(email)=lower(auth.jwt()->>'email')));

grant select,insert,update,delete on public.resource_links to authenticated;
grant select on public.ai_health_eval_runs to authenticated;
grant usage,select on sequence public.resource_links_id_seq,public.ai_health_eval_runs_id_seq to authenticated;

update public.marking_scheme_answers
set component_variant_code=concat(paper_number,variant),
    answer_text=coalesce(answer_text,clean_answer_text),
    marking_points_json=coalesce(to_jsonb(marking_points),'[]'::jsonb),
    raw_text=coalesce(raw_text,raw_answer_text),
    bounding_box=coalesce(bounding_box,bbox)
where true;

update public.question_index
set marking_scheme_status=case
  when marking_scheme_link_status in ('linked','linked_exact') and marking_scheme_answer_id is not null then 'linked'
  when marking_scheme_link_status='needs_review' then 'needs_review'
  else 'resource_missing'
end;
