alter table public.marking_scheme_answers
  add column if not exists answer_type text not null default 'unknown'
    check(answer_type in ('question_answer','generic_guidance','examiner_note','header_footer','unknown','needs_review')),
  add column if not exists is_question_specific boolean not null default false,
  add column if not exists extraction_confidence numeric(4,3)
    check(extraction_confidence is null or extraction_confidence between 0 and 1),
  add column if not exists normalized_text text,
  add column if not exists detection_reason text,
  add column if not exists link_reason text,
  add column if not exists question_id bigint references public.question_index(id) on delete set null,
  add column if not exists link_confidence numeric(4,3)
    check(link_confidence is null or link_confidence between 0 and 1),
  add column if not exists linked_status text not null default 'unlinked'
    check(linked_status in ('linked','partial','unlinked','needs_review'));

create table if not exists public.marking_scheme_link_audits (
  id bigint generated by default as identity primary key,
  question_id bigint references public.question_index(id) on delete set null,
  marking_scheme_answer_id bigint references public.marking_scheme_answers(id) on delete set null,
  action text not null,
  reason text not null,
  old_status text,
  metadata_json jsonb not null default '{}',
  created_at timestamptz not null default now()
);
alter table public.marking_scheme_link_audits enable row level security;
create policy "Admins read marking scheme link audits" on public.marking_scheme_link_audits
  for select to authenticated
  using(exists(select 1 from public.admin_users a where lower(a.email)=lower(auth.jwt()->>'email')));
grant select on public.marking_scheme_link_audits to authenticated;
grant usage,select on sequence public.marking_scheme_link_audits_id_seq to authenticated;

update public.marking_scheme_answers
set answer_type='generic_guidance',is_question_specific=false,extraction_confidence=greatest(coalesce(extraction_confidence,confidence),0.95),
    detection_reason='Backfill: matched generic marking-guidance language',normalized_text=coalesce(normalized_text,clean_answer_text),linked_status='needs_review'
where coalesce(raw_answer_text,clean_answer_text,'') ~* '(general marking principles|calculation specific guidance|correct answers? to calculations? should be given full credit|significant figures?|examiners? should|mark scheme is published as an aid|mark schemes? should be read in conjunction|generic guidance|marking principles)';

update public.marking_scheme_answers
set answer_type='question_answer',is_question_specific=true,
    extraction_confidence=coalesce(extraction_confidence,confidence),normalized_text=coalesce(normalized_text,clean_answer_text),
    detection_reason=coalesce(detection_reason,'Backfill: numbered extracted answer')
where answer_type='unknown' and question_number ~ '^[0-9]{1,2}$'
  and (coalesce(extraction_confidence,confidence)>=0.90 or trim(clean_answer_text) ~ '^[A-D]$')
  and length(trim(coalesce(clean_answer_text,'')))>0
  and coalesce(raw_answer_text,clean_answer_text,'') !~* '(general marking principles|calculation specific guidance|correct answers? to calculations? should be given full credit|significant figures?|examiners? should|mark scheme is published as an aid|mark schemes? should be read in conjunction|generic guidance|marking principles)';

update public.marking_scheme_answers
set answer_type='needs_review',is_question_specific=false,extraction_confidence=coalesce(extraction_confidence,confidence),
    normalized_text=coalesce(normalized_text,clean_answer_text),detection_reason=coalesce(detection_reason,'Backfill: confidence insufficient for official question answer'),linked_status='needs_review'
where answer_type='unknown';

insert into public.marking_scheme_link_audits(question_id,marking_scheme_answer_id,action,reason,old_status,metadata_json)
select q.id,q.marking_scheme_answer_id,'unlinked_invalid','Generic or non-question-specific marking-scheme section was linked as an official answer',q.marking_scheme_link_status,
       jsonb_build_object('question_number',q.question_number,'answer_type',a.answer_type,'answer_question_number',a.question_number)
from public.question_index q join public.marking_scheme_answers a on a.id=q.marking_scheme_answer_id
where a.answer_type<>'question_answer' or not a.is_question_specific
   or a.question_number<>regexp_replace(q.question_number,'^([0-9]+).*','\1')
   or (a.question_part is not null and replace(coalesce(q.question_part,''),' ','')<>replace(a.question_part,' ',''));

update public.question_index q
set answer_text=null,marking_scheme_answer_id=null,marking_scheme_link_status='needs_review',marking_scheme_link_confidence=null,updated_at=now()
from public.marking_scheme_answers a
where a.id=q.marking_scheme_answer_id
  and (a.answer_type<>'question_answer' or not a.is_question_specific
    or a.question_number<>regexp_replace(q.question_number,'^([0-9]+).*','\1')
    or (a.question_part is not null and replace(coalesce(q.question_part,''),' ','')<>replace(a.question_part,' ','')));
