alter table public.resources
  add column if not exists detected_metadata_json jsonb not null default '{}',
  add column if not exists detection_status text not null default 'not_checked'
    check (detection_status in ('not_checked','ready','needs_review','conflict','duplicate','unsupported','failed')),
  add column if not exists detection_warnings_json jsonb not null default '[]',
  add column if not exists normalized_paper_code text,
  add column if not exists duplicate_of_resource_id bigint references public.resources(id) on delete set null;

alter table public.admin_import_batches
  add column if not exists ready_count integer not null default 0,
  add column if not exists conflict_count integer not null default 0,
  add column if not exists uploaded_count integer not null default 0,
  add column if not exists processing_count integer not null default 0,
  add column if not exists completed_count integer not null default 0,
  add column if not exists updated_at timestamptz not null default now();
alter table public.admin_import_batches drop constraint if exists admin_import_batches_status_check;
alter table public.admin_import_batches add constraint admin_import_batches_status_check check(status in (
  'uploading','detecting','ready_for_review','importing','processing','completed','completed_with_errors','failed','cancelled',
  'previewed'
));

create table if not exists public.import_batch_files (
  id bigint generated by default as identity primary key,
  import_batch_id bigint not null references public.admin_import_batches(id) on delete cascade,
  original_filename text not null,
  file_size bigint,
  mime_type text,
  storage_bucket text not null default 'resources',
  storage_path text,
  file_hash text,
  upload_status text not null default 'queued'
    check(upload_status in ('queued','uploading','uploaded','upload_failed','cancelled')),
  detected_metadata_json jsonb not null default '{}',
  detection_confidence integer,
  detection_status text not null default 'needs_review'
    check (detection_status in ('queued','detecting','ready','needs_review','conflict','duplicate','unsupported','detection_failed','detection_timed_out','cancelled')),
  import_status text not null default 'pending'
    check(import_status in ('pending','importing','imported','import_failed','skipped','cancelled')),
  processing_status text not null default 'pending'
    check(processing_status in ('pending','queued','processing','completed','failed','needs_review','cancelled')),
  warnings_json jsonb not null default '[]',
  conflicts_json jsonb not null default '[]',
  admin_overrides_json jsonb not null default '{}',
  final_resource_id bigint references public.resources(id) on delete set null,
  processing_job_id bigint references public.processing_jobs(id) on delete set null,
  duplicate_of_resource_id bigint references public.resources(id) on delete set null,
  error_message text,
  error_step text,
  retry_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists import_batch_files_batch_idx on public.import_batch_files(import_batch_id,detection_status);
alter table public.import_batch_files enable row level security;
create policy "Import batch files manageable by admins" on public.import_batch_files
  for all to authenticated
  using (exists(select 1 from public.admin_users a where lower(a.email)=lower(auth.jwt()->>'email')))
  with check (exists(select 1 from public.admin_users a where lower(a.email)=lower(auth.jwt()->>'email')));
grant select,insert,update,delete on public.import_batch_files to authenticated;
grant usage,select on sequence public.import_batch_files_id_seq to authenticated;

create table if not exists public.cambridge_component_mappings (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  syllabus_code text not null,
  level public.study_level not null,
  component_number integer not null check (component_number between 1 and 9),
  display_name text not null,
  allowed_variants integer[] not null default '{}',
  active_from_year integer not null default 2000,
  active_to_year integer,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(subject_id,component_number,active_from_year)
);
create index if not exists cambridge_component_lookup_idx on public.cambridge_component_mappings(syllabus_code,component_number,active_from_year,active_to_year);
alter table public.cambridge_component_mappings enable row level security;
create policy "Component mappings readable by signed-in users" on public.cambridge_component_mappings
  for select to authenticated using (true);
create policy "Component mappings manageable by admins" on public.cambridge_component_mappings
  for all to authenticated
  using (exists(select 1 from public.admin_users a where lower(a.email)=lower(auth.jwt()->>'email')))
  with check (exists(select 1 from public.admin_users a where lower(a.email)=lower(auth.jwt()->>'email')));
grant select,insert,update,delete on public.cambridge_component_mappings to authenticated;
grant usage,select on sequence public.cambridge_component_mappings_id_seq to authenticated;

insert into public.cambridge_component_mappings(subject_id,syllabus_code,level,component_number,display_name,allowed_variants)
select s.id,v.code,s.level,v.component,v.label,array[1,2,3]
from (values
  ('9709',1,'Paper 1 Pure Mathematics 1'),('9709',2,'Paper 2 Pure Mathematics 2'),
  ('9709',3,'Paper 3 Pure Mathematics 3'),('9709',4,'Paper 4 Mechanics'),
  ('9709',5,'Paper 5 Probability & Statistics 1'),('9709',6,'Paper 6 Probability & Statistics 2'),
  ('9702',1,'Paper 1 Multiple Choice'),('9702',2,'Paper 2 AS Level Structured Questions'),
  ('9702',3,'Paper 3 Advanced Practical Skills'),('9702',4,'Paper 4 A Level Structured Questions'),
  ('9702',5,'Paper 5 Planning, Analysis and Evaluation'),
  ('9701',1,'Paper 1 Multiple Choice'),('9701',2,'Paper 2 AS Level Structured Questions'),
  ('9701',3,'Paper 3 Advanced Practical Skills'),('9701',4,'Paper 4 A Level Structured Questions'),
  ('9701',5,'Paper 5 Planning, Analysis and Evaluation')
) as v(code,component,label)
join public.subjects s on lpad(s.code,4,'0')=v.code
on conflict do nothing;
