alter table public.question_index
  add column if not exists difficulty_reason text,
  add column if not exists difficulty_confidence numeric(4,3);

alter table public.paper_check_submissions
  add column if not exists uploaded_file_deleted boolean not null default false,
  add column if not exists uploaded_file_deleted_at timestamptz,
  add column if not exists file_retention_status text not null default 'temporary'
    check (file_retention_status in ('temporary','deleted','retained','expired','deletion_failed')),
  add column if not exists report_saved boolean not null default false,
  add column if not exists expires_at timestamptz;

create table if not exists public.student_learning_profile (
  user_id uuid primary key references auth.users(id) on delete cascade,
  preferred_answer_style text not null default 'teacher',
  last_subject_id bigint references public.subjects(id) on delete set null,
  last_studied_at timestamptz,
  total_questions_viewed integer not null default 0,
  total_questions_attempted integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.student_topic_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  topic text not null,
  subtopic text not null default '',
  viewed_count integer not null default 0,
  attempted_count integer not null default 0,
  correct_count integer not null default 0,
  mastery_score numeric(5,2) not null default 0 check (mastery_score between 0 and 100),
  last_studied_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(user_id,subject_id,topic,subtopic)
);

create table if not exists public.student_question_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.question_index(id) on delete cascade,
  activity_type text not null check (activity_type in ('viewed','attempted','completed','saved')),
  is_correct boolean,
  awarded_marks numeric,
  max_marks numeric,
  source text not null default 'question_bank',
  created_at timestamptz not null default now()
);

create table if not exists public.student_mistake_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint references public.question_index(id) on delete set null,
  submission_id uuid references public.paper_check_submissions(id) on delete set null,
  subject_id bigint references public.subjects(id) on delete cascade,
  topic text,
  subtopic text,
  mistake_type text not null,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists student_topic_progress_user_idx on public.student_topic_progress(user_id,mastery_score);
create index if not exists student_question_activity_user_idx on public.student_question_activity(user_id,created_at desc);
create index if not exists student_mistake_history_user_idx on public.student_mistake_history(user_id,created_at desc);

alter table public.student_learning_profile enable row level security;
alter table public.student_topic_progress enable row level security;
alter table public.student_question_activity enable row level security;
alter table public.student_mistake_history enable row level security;

grant select,insert,update,delete on public.student_learning_profile to authenticated;
grant select,insert,update,delete on public.student_topic_progress to authenticated;
grant select,insert,update,delete on public.student_question_activity to authenticated;
grant select,insert,update,delete on public.student_mistake_history to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create policy "Learning profile owned access" on public.student_learning_profile for all to authenticated
  using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "Topic progress owned access" on public.student_topic_progress for all to authenticated
  using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "Question activity owned access" on public.student_question_activity for all to authenticated
  using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "Mistake history owned access" on public.student_mistake_history for all to authenticated
  using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
